GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTYzNTk5MjQ1MiwiZXhwIjoxNjM1OTkyNDY3fQ.KK8kDujsFqhRuaHbfb-hzZ0JI_02aA55KAYxKSFKkyM

###


POST  http://localhost:4000/token
Content-Type: application/json

{
    "token":
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTYzNTk5MjQ1Mn0.2jPmlRn4jXjDmWTIAcbZyG78FXXGYh41u7bd2Nm4Eyg"
}
###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTYzNTk5Mjg2MH0.r8hhYuyKrDN0-9zpRmkUp1LWndZ6_bEGNHqNKSa4OY4"
}


###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"kyle"
}